#!/bin/bash

# File and folder names
ssDIR="$HOME/Pictures/Screenshots"
file="$ssDIR/$(date +'%Y-%m-%d_%H-%M-%S_screenshot.png')"
exfile="${file/#\~/$HOME}"
sDIR="$HOME/.config/hypr/scripts"

mkdir -p -- "$ssDIR"

fullscreen() {
    wayshot -f "$exfile"
    # swappy -f "$exfile" -o "$exfile"

    if wl-copy < "$exfile"; then
      notify-send -u low "Screenshot Saved" "File saved to '<i>$ssDIR</i>'" -i "$exfile"
    fi

    # "$sDIR/Sounds.sh" --screenshot
}

region() {
    wayshot -s "$(slurp)" -f "$exfile"
    # swappy -f "$exfile" -o "$exfile"
     
    if wl-copy < "$exfile"; then
      notify-send -u low "Screenshot Saved" "File saved to '<i>$ssDIR</i>'" -i "$exfile"
    fi

    # "$sDIR/Sounds.sh" --screenshot
}

if [[ "$1" == "--selection" ]]; then
    region
elif [[ "$1" == "--full" ]]; then
    fullscreen
else
    wayshot --stdout | wl-copy
fi
