[colors.primary]
background = '#1a1112'
foreground = '#f0dede'

[colors.cursor]
text = '#d7c1c2'
cursor = '#f0dede'

[colors.normal]
black   = '#4c4c4c'
red     = '#ac8a8c'
green   = '#8aac8b'
yellow  = '#aca98a'
blue    = '#ffb2b7'
magenta = '#ac8aac'
cyan    = '#8aacab'
white   = '#f0f0f0'

[colors.bright]
black   = '#262626'
red     = '#c49ea0'
green   = '#9ec49f'
yellow  = '#c4c19e'
blue    = '#a39ec4'
magenta = '#c49ec4'
cyan    = '#9ec3c4'
white   = '#e7e7e7'
