
[colors.primary]
background = '#0D0C0C'
foreground = '#EBE9E6'

[colors.cursor]
text = '#DAD7D3'
cursor = '#EBE9E6'

# Normal colors
[colors.normal]
black   = '#999793'
red     = '#433E3B'
green   = '#4A4542'
yellow  = '#BD383B'
blue    = '#76736F'
magenta = '#797773'
cyan    = '#C6C0B7'
white   = '#DAD7D3'

# Bright colors
[colors.bright]
black   = '#0D0C0C'
red     = '#322E2C'
green   = '#373431'
yellow  = '#8E2A2C'
blue    = '#585754'
magenta = '#5B5956'
cyan    = '#959089'
white   = '#DAD7D3'
