
[colors.primary]
background = '#131214'
foreground = '#EFEFF0'

[colors.cursor]
text = '#DFDFE2'
cursor = '#EFEFF0'

# Normal colors
[colors.normal]
black   = '#9C9C9E'
red     = '#5E5B65'
green   = '#65626C'
yellow  = '#8C8288'
blue    = '#908E96'
magenta = '#C9C9CE'
cyan    = '#D0D0D5'
white   = '#DFDFE2'

# Bright colors
[colors.bright]
black   = '#131214'
red     = '#47444C'
green   = '#4C4A51'
yellow  = '#696166'
blue    = '#6C6B70'
magenta = '#97979A'
cyan    = '#9C9CA0'
white   = '#DFDFE2'
