
[colors.primary]
background = '#030609'
foreground = '#D4DBDC'

[colors.cursor]
text = '#B9C3C5'
cursor = '#D4DBDC'

# Normal colors
[colors.normal]
black   = '#81888A'
red     = '#182532'
green   = '#274F62'
yellow  = '#4A5A64'
blue    = '#8C6569'
magenta = '#75888E'
cyan    = '#83979C'
white   = '#B9C3C5'

# Bright colors
[colors.bright]
black   = '#030609'
red     = '#121B26'
green   = '#1D3B4A'
yellow  = '#37444B'
blue    = '#694C4F'
magenta = '#58666A'
cyan    = '#627175'
white   = '#B9C3C5'
