
[colors.primary]
background = '#020506'
foreground = '#D7D3D5'

[colors.cursor]
text = '#BDB7BA'
cursor = '#D7D3D5'

# Normal colors
[colors.normal]
black   = '#848082'
red     = '#112126'
green   = '#31252D'
yellow  = '#5A2F3A'
blue    = '#4B4E53'
magenta = '#847A80'
cyan    = '#8C8086'
white   = '#BDB7BA'

# Bright colors
[colors.bright]
black   = '#020506'
red     = '#0D191D'
green   = '#251C22'
yellow  = '#43232C'
blue    = '#383A3E'
magenta = '#635B60'
cyan    = '#696064'
white   = '#BDB7BA'
