
[colors.primary]
background = '#09090A'
foreground = '#F6EBC9'

[colors.cursor]
text = '#EADAA9'
cursor = '#F6EBC9'

# Normal colors
[colors.normal]
black   = '#A49876'
red     = '#905F51'
green   = '#5F7792'
yellow  = '#FB5D7C'
blue    = '#B29CF1'
magenta = '#75CBDF'
cyan    = '#E6C564'
white   = '#EADAA9'

# Bright colors
[colors.bright]
black   = '#09090A'
red     = '#6C473D'
green   = '#47596E'
yellow  = '#BC465D'
blue    = '#8675B5'
magenta = '#5898A7'
cyan    = '#AC944B'
white   = '#EADAA9'
