
[colors.primary]
background = '#07090A'
foreground = '#E0E0E3'

[colors.cursor]
text = '#CACACE'
cursor = '#E0E0E3'

# Normal colors
[colors.normal]
black   = '#8D8D90'
red     = '#293234'
green   = '#5D5351'
yellow  = '#776460'
blue    = '#CD3D0E'
magenta = '#F87532'
cyan    = '#A6A5AE'
white   = '#CACACE'

# Bright colors
[colors.bright]
black   = '#07090A'
red     = '#1F2627'
green   = '#463F3D'
yellow  = '#594B48'
blue    = '#9A2E0A'
magenta = '#BA5825'
cyan    = '#7C7C83'
white   = '#CACACE'
