#!/bin/bash
# fake big mac

user=$(whoami)
session="$(loginctl session-status | head -n 1 | awk '{print $1}')"

if command -v kitty > /dev/null 2>&1; then
    tty="kitty"
elif command -v alacritty > /dev/null 2>&1; then
    tty="alacritty"
fi

if command -v neofetch > /dev/null 2>&1; then
    fetch="neofetch"
elif command -v fastfetch > /dev/null 2>&1; then
    fetch="fastfetch"
fi

entry() {
  n_left=$(wc -c <<< "$1")
  if [ -z "$2" ]; then
    printf "%s" "$1"
    return
  fi
  pad=$(( $3 - n_left ))
  printf "%s%${pad}s" "$1" "$2"
}

choice1=" About This PC"

if [ -f "$HOME/.cache/updcount" ]; then
  updates="$(cat "$HOME/.cache/updcount")"
fi

if [ "$updates" = "0" ]; then
  choice2="$(entry " System Updates..." "􀁢 " 53)"
else
  numlen=$(wc -c <<< "$updates")
  case "$numlen" in
    2) width=43 ;;
    3) width=41 ;;
    4) width=41 ;;
  esac

  if [ "$updates" = "1" ]; then
    grammer=update
  else
    grammer=updates
  fi

  choice2="$(entry " System Updates..." "$updates $grammer" $width)"
fi

choice3="$(entry " Sleep")"
choice4="$(entry " Restart...")"
choice5="$(entry " Shut Down...")"
choice6="$(entry " Lock Screen" "⌃ ⌘ Q" 57)"
choice7="$(entry " Log Out $user..." "􀆝 ⌘ Q" 55)"

menu=$(printf "%s\n%s\n%s\n%s\n%s\n%s\n%s\n" "$choice1" "$choice2" "$choice3" "$choice4" "$choice5" "$choice6" "$choice7" | rofi -dmenu -config ~/.config/rofi/menu.rasi -i -no-show-icons -l 7 -width 30 -replace)

case "$menu" in
  "$choice1") $tty --title "$fetch" -e bash -i -c "$fetch && sleep infinity" ;;
  "$choice2") $tty --title "System Updates" -e bash -i -c "updater" ;;
  "$choice3") sleep 0.1 && hyprctl dispatch dpms off && systemctl suspend-then-hibernate ;;
  "$choice4") systemctl reboot ;;
  "$choice5") systemctl poweroff ;;
  "$choice6") hyprlock ;;
  "$choice7") loginctl terminate-session "$session";;
esac
